import Vue from 'vue';

// import the required components from iview
import {
  // Affix,
  // Alert,
  // AutoComplete,
  // Avatar,
  // BackTop,
  // Badge,
  // Breadcrumb,
  // BreadcrumbItem,
  Button,
  // ButtonGroup,
  Card,
  Carousel,
  CarouselItem,
  Cascader,
  Checkbox,
  CheckboxGroup,
  Circle,
  Col,
  // Collapse,
  // ColorPicker,
  // Content,
  DatePicker,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  // Footer,
  Form,
  FormItem,
  // Header,
  Icon,
  Input,
  InputNumber,
  // Scroll,
  // Sider,
  Submenu,
  // Layout,
  LoadingBar,
  Menu,
  // MenuGroup,
  MenuItem,
  // Message,
  Modal,
  Notice,
  Option,
  // OptionGroup,
  Page,
  // Panel,
  Poptip,
  // Progress,
  Radio,
  RadioGroup,
  // Rate,
  Row,
  Select,
  Slider,
  Spin,
  Step,
  Steps,
  Table,
  // Tabs,
  // TabPane,
  Tag,
  // Timeline,
  // TimelineItem,
  // TimePicker,
  Tooltip,
  // Transfer,
  Tree,
  // Upload
} from 'iview';

// map of required components
const componentsMap = {
  // 'Affix': Affix,
  // 'Alert': Alert,
  // 'AutoComplete': AutoComplete,
  // 'Avatar': Avatar,
  // 'BackTop': BackTop,
  // 'Badge': Badge,
  // 'Breadcrumb': Breadcrumb,
  // 'BreadcrumbItem': BreadcrumbItem,
  'Button': Button,
  // 'ButtonGroup': ButtonGroup,
  'Card': Card,
  'Carousel': Carousel,
  'CarouselItem': CarouselItem,
  'Cascader': Cascader,
  'Checkbox': Checkbox,
  'CheckboxGroup': CheckboxGroup,
  'ICircle': Circle,
  'Col': Col,
  // 'Collapse': Collapse,
  // 'ColorPicker': ColorPicker,
  // 'Content': Content,
  'DatePicker': DatePicker,
  'Dropdown': Dropdown,
  'DropdownItem': DropdownItem,
  'DropdownMenu': DropdownMenu,
  // 'Footer': Footer,
  'Form': Form,
  'FormItem': FormItem,
  // 'Header': Header,
  'Icon': Icon,
  'Input': Input,
  'InputNumber': InputNumber,
  // 'Scroll': Scroll,
  // 'Sider': Sider,
  'Submenu': Submenu,
  // 'Layout': Layout,
  'LoadingBar': LoadingBar,
  'Menu': Menu,
  // 'MenuGroup': MenuGroup,
  'MenuItem': MenuItem,
  // 'Message': Message,
  'Modal': Modal,
  'Notice': Notice,
  'Option': Option,
  // 'OptionGroup': OptionGroup,
  'Page': Page,
  // 'Panel': Panel,
  'Poptip': Poptip,
  // 'Progress': Progress,
  'Radio': Radio,
  'RadioGroup': RadioGroup,
  // 'Rate': Rate,
  'Row': Row,
  'Select': Select,
  'Slider': Slider,
  'Spin': Spin,
  'Step': Step,
  'Steps': Steps,
  'Table': Table,
  // 'Tabs': Tabs,
  // 'TabPane': TabPane,
  'Tag': Tag,
  // 'Timeline': Timeline,
  // 'TimelineItem': TimelineItem,
  // 'TimePicker': TimePicker,
  'Tooltip': Tooltip,
  // 'Transfer': Transfer,
  'Tree': Tree,
  // 'Upload': Upload,
};

// loop to register the required components
Object.entries(componentsMap).forEach(item => Vue.component(item[0], item[1]));

